### ISSUE TITLE
Barra de actividades: modificar para que funcione con imagen

### ISSUE THREAD

**Issue by ran-research-lab** [Nicole-M-Ramirez/rio-Test#3]
Asegurarse de que no muestra la barra de Back. Asignar funcionalidad a botones imaginarios.

**Comment by Nicole-M-Ramirez** [comment]
Ya repare el header. Ya en todas las pantallas en las que aparesia el boton de back ya no aparese el header, solo el boton

**Comment by ran-research-lab** [comment]
Buen!

--
________________________________
